@FichajeDeEmpresa.Api_HostAddress = http://localhost:5050

### Health
GET {{FichajeDeEmpresa.Api_HostAddress}}/api/health
Accept: application/json

### Login correcto admin
POST {{FichajeDeEmpresa.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "admin",
  "password": "admin"
}

### Login correcto user
POST {{FichajeDeEmpresa.Api_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "user",
  "password": "user"
}

### Fichar entrada admin
POST {{FichajeDeEmpresa.Api_HostAddress}}/api/fichajes/entrada
Content-Type: application/json

{
  "userId": 1
}

### Fichar salida admin
POST {{FichajeDeEmpresa.Api_HostAddress}}/api/fichajes/salida
Content-Type: application/json

{
  "userId": 1
}

### Resumen de hoy admin
GET {{FichajeDeEmpresa.Api_HostAddress}}/api/fichajes/resumen-hoy/1
Accept: application/json

### Resumen de hoy user
GET {{FichajeDeEmpresa.Api_HostAddress}}/api/fichajes/resumen-hoy/2
Accept: application/json